import type { Article } from "./index";

export const skolkoTratitNaReklamuFormulaByudzhetaDlyaMalogoArticle: Article = {
  contentType: "article",
  tags: ["Реклама"],
  service: null,
  industry: null,
  priority: 50,
  seoTitle: `Сколько тратить на рекламу: расчет рекламного бюджета для малого бизнеса`,
  description: `Узнайте, сколько тратить на рекламу и как рассчитать рекламный бюджет малого бизнеса. Простая формула поможет распределить расходы и избежать ошибок.`,
  category: `Реклама`,
  date: `2 октября 2025`,
  updatedAt: `2 октября 2025`,
  cover: undefined,
  author: `Make All Perfect`,
  authorRole: `Команда Make All Perfect`,
  slug: `skolko-tratit-na-reklamu-formula-byudzheta-dlya-malogo-biznesa`,
  url: `/blog/skolko-tratit-na-reklamu-formula-byudzheta-dlya-malogo-biznesa`,
  title: `Сколько тратить на рекламу: формула бюджета для малого бизнеса`,
  body: [
  { type: "h2", content: `Почему важно правильно считать рекламный бюджет`, showInContent: true },
  { type: "text", content: `В бизнесе реклама — это не просто строка расходов. Это как топливо для автомобиля: можно заправить чуть-чуть и ехать «на лампочке», постоянно рискуя встать посреди трассы. А можно залить полный бак, но поехать без карты и сжечь всё топливо впустую.` },
  { type: "text", content: `Малый бизнес часто попадает именно в эти крайности. Кто-то выделяет «сколько осталось» после зарплат и аренды, а кто-то, наоборот, тратит всё подряд в надежде на чудо. Итог одинаковый — рекламные кампании не приносят клиентов, и предприниматель делает вывод: «Реклама не работает». На самом деле не работает не реклама, а подход без расчётов.` },
  { type: "h2", content: `Какие факторы влияют на размер рекламного бюджета`, showInContent: true },
  { type: "h3", content: `Размер бизнеса и стадия развития` },
  { type: "text", content: `Стартап, который только выходит на рынок, и кофейня с трёхлетней историей — это две разные задачи. Первому нужно громко заявить о себе, второму — удерживать постоянных гостей и искать новые точки роста.` },
  { type: "h3", content: `Отрасль и конкуренция` },
  { type: "text", content: `В нишах вроде<a href="https://makeallperfect.ru/services/nishevoe-prodvizhenie"> недвижимости или юридических услуг</a> клик в контексте может стоить дороже чашки кофе. А если вы продаёте торты на заказ в небольшом городе — бюджеты будут скромнее.` },
  { type: "h3", content: `Цели продвижения` },
  { type: "text", content: `Хотите больше заказов здесь и сейчас? Тогда нужны лиды. Запускаете новый<a href="https://makeallperfect.ru/services/prodvizhenie-magazinov-na-marketpleysah"> бренд одежды на маркетплейсе</a>? Работайте на узнаваемость. У каждой цели свой чек и свой бюджет.` },
  { type: "h3", content: `Средний чек и маржинальность` },
  { type: "text", content: `Продвигать товар за 500 рублей и за 50 000 — разные истории. При высоком чеке можно позволить себе более дорогие каналы. При низком — важно считать каждую копейку и искать эффективные связки.` },
  { type: "h3", content: `Сезонность и акции` },
  { type: "text", content: `В<a href="/blog/kak-pravilno-planirovat-reklamnyy-byudzhet-k-chernoy-pyatnitse"> «Чёрную пятницу»</a> рекламные ставки взлетают, и те, кто не заложил запас, остаются «за бортом». А в январе, наоборот, реклама дешевле, и этим можно воспользоваться.` },
  { type: "h2", content: `Подходы и формулы расчёта рекламного бюджета`, showInContent: true },
  { type: "h3", content: `Метод «от оборота»` },
  { type: "text", content: `Классика: 5–15% от выручки. Для малого бизнеса это оптимальный ориентир. Если оборот 1 млн рублей — значит, 50–150 тысяч можно смело инвестировать в рекламу.` },
  { type: "h3", content: `Метод «от цели»` },
  { type: "text", content: `Считаем от обратного: нужно 100 новых заказов, средняя стоимость лида — 500 рублей. Бюджет = 50 000. Просто, прозрачно и удобно для планирования.` },
  { type: "h3", content: `Метод тестового бюджета` },
  { type: "text", content: `Никто не знает, какой канал сработает лучше именно для вас. Поэтому выделяют 10–20% бюджета на тест, пробуют разные гипотезы, а потом масштабируют успешные.` },
  { type: "h3", content: `Формула «часть постоянных расходов»` },
  { type: "text", content: `Некоторые эксперты советуют воспринимать маркетинг как аренду или зарплаты: обязательную статью расходов. Тогда вопрос «тратить или не тратить» не встаёт — остаётся только решать, куда именно инвестировать.` },
  { type: "h3", content: `Подход через CPA и ROI` },
  { type: "text", content: `Если цель — не просто заявки, а прибыль, считаем так: стоимость привлечения клиента (CPA) должна быть меньше прибыли с продажи, а возврат на инвестиции (ROI) — в плюсе.` },
  { type: "h2", content: `Примеры расчёта рекламного бюджета`, showInContent: true },
  { type: "image", src: `/assets/images/68de6607d908dd36e81c63cf.webp`, alt: `формула рекламного бюджета`, imageStyle: "default", showInContent: true, quoteAfter: false, ctaAfter: false, content: "" },
  { type: "h3", content: `Малый бизнес с оборотом 1 млн руб.` },
  { type: "text", content: `Берём 10% → 100 000 рублей в месяц. Распределяем: 40%<a href="https://makeallperfect.ru/services/contecstnaya-reklama"> контекстная реклама</a>, 30% соцсети, 20%<a href="https://makeallperfect.ru/services/seo"> SEO</a>, 10%<a href="https://makeallperfect.ru/services/upravleniye-reputatsiyey-i-pr"> PR и имидж</a>.` },
  { type: "h3", content: `Стартап, выходящий на рынок` },
  { type: "text", content: `Допустим, у вас всего 50 000 рублей. Логично вложить 70% в быстрые каналы (Яндекс Директ + Google Ads) и 30% в долгосрочные (SEO, контент).` },
  { type: "h3", content: `Интернет-магазин на маркетплейсах` },
  { type: "text", content: `Вы хотите 200 заказов в месяц, средний CPL — 400 рублей. Значит, минимальный бюджет = 80 000 рублей. Здесь стоит подключить<a href="https://makeallperfect.ru/services/prodvizhenie-magazinov-na-marketpleysah"> рекламу внутри маркетплейсов</a>.` },
  { type: "h2", content: `Как распределить рекламный бюджет между каналами`, showInContent: true },
  { type: "h3", content: `Контекстная реклама` },
  { type: "text", content: `<a href="https://makeallperfect.ru/services/reklama-yandex-direct">Яндекс Директ</a> и<a href="https://makeallperfect.ru/services/reklama-google-ads"> Google Ads</a> дают быстрые заявки, но требуют чёткой аналитики.` },
  { type: "h3", content: `Социальные сети` },
  { type: "text", content: `<a href="https://makeallperfect.ru/services/targetirovannaya-reklama">Таргетированная реклама</a> во<a href="https://makeallperfect.ru/services/reklama-vkontakte"> ВКонтакте</a> или<a href="https://makeallperfect.ru/services/reklama-telegram-ads"> Telegram Ads</a> работает там, где ваша аудитория проводит время.` },
  { type: "h3", content: `SEO и контент-маркетинг` },
  { type: "text", content: `Не даёт мгновенного результата, но через полгода способно приносить клиентов дешевле контекста. Подробнее см. раздел<a href="https://makeallperfect.ru/services/seo-prodvizhenie"> SEO-продвижение</a>.` },
  { type: "h3", content: `Реклама на маркетплейсах` },
  { type: "text", content: `Если вы торгуете на WB или Ozon, внутреннее продвижение становится обязательным — подробнее об этом в разделе<a href="https://makeallperfect.ru/services/prodvizhenie-magazinov-na-marketpleysah"> услуг для e-commerce</a>.` },
  { type: "h3", content: `PR и офлайн` },
  { type: "text", content: `Не стоит недооценивать<a href="https://makeallperfect.ru/services/publikatsii-v-smi"> публикации в СМИ</a>, локальные мероприятия и коллаборации — для малого бизнеса это иногда «волшебный пинок».` },
  { type: "h2", content: `Типичные ошибки при планировании бюджета`, showInContent: true },
  { type: "text", content: `<ul><li>Вкладываться только в один канал.</li><li>Пытаться «протестировать» рекламу за 5 тысяч рублей.</li><li>Не подключать аналитику и не знать, откуда пришёл клиент.</li><li>Копировать бюджеты конкурентов, не считая собственную экономику.</li></ul>` },
  { type: "h2", content: `Как оптимизировать бюджет, если ресурсов мало`, showInContent: true },
  { type: "text", content: `<ul><li>Выберите один канал и доведите его до предела эффективности.</li><li>Работайте с органикой: SEO, группы в соцсетях, сарафанное радио.</li><li>Тестируйте гипотезы маленькими шагами.</li><li>Подключайте автоматизацию и аналитику, чтобы не платить за воздух.</li></ul>` },
  { type: "h2", content: `Чек-лист для предпринимателя`, showInContent: true },
  { type: "text", content: `<ul><li>Определи цель: заявки, продажи, узнаваемость.</li><li>Выбери формулу расчёта бюджета.</li><li>Закладывай минимум 5–10% от оборота.</li><li>Делай тесты и масштабируй удачные связки.</li><li>Пересматривай результаты каждый месяц.</li></ul>` },
  { type: "h2", content: `Заключение`, showInContent: true },
  { type: "text", content: `Реклама — это не «дополнительные расходы». Это инвестиция, которая либо растит ваш бизнес, либо сливается в песок. Экономия здесь опаснее, чем разумные вложения: сэкономив 30 тысяч на рекламе, можно потерять 300 тысяч выручки.` },
  { type: "text", content: `Если вам сложно самому рассчитать бюджет и понять, куда идти — доверьтесь экспертам. Посмотрите наши<a href="https://makeallperfect.ru/cases"> кейсы</a>, изучите раздел<a href="https://makeallperfect.ru/services"> услуг</a>, загляните в<a href="https://makeallperfect.ru/useful?utm_source=chatgpt.com"> полезные статьи</a> и<a href="https://makeallperfect.ru/reviews"> отзывы клиентов</a>. Мы помогаем бизнесу расти без лишних трат.` },
],
  relatedArticles: [
    { title: `Как рассчитать рекламный бюджет, чтобы не слить деньги впустую`, description: `Точные формулы расчёта рекламного бюджета под ваш случай. Разбираем реальные цифры: сколько платят за клик, как не...`, href: `/blog/kak-rasschitat-reklamnyy-byudzhet-chtoby-ne-slit-dengi-vpustuyu`, label: `Реклама` },
    { title: `Внешняя реклама для маркетплейсов: как выстрелить и не промахнуться`, description: `Реальные кейсы: +1100% заказов на Ozon и х4 продаж на Wildberries. Разбираем стратегии внешней рекламы, работающие в...`, href: `/blog/vneshnyaya-reklama-dlya-marketplejsov-kak-vystrelit-i-ne-promahnutsya`, label: `Маркетинг` },
    { title: `Реклама в ВКонтакте: как в 2025 году настроить её так, чтобы был результат`, description: `Как работает реклама ВКонтакте (VK Ads) Цена, таргетинг, примеры форматов и советы по настройке рекламных кампаний.`, href: `/blog/reklama-v-vkontakte-kak-v-2025-godu-nastroit-ee-tak-chtoby-byl-rezultat`, label: `Реклама` },
  ],
  relatedCases: [
    { title: `Увеличили онлайн-продажи в 2,4 раза для бренда одежды за 4 месяца`, description: `Российский бренд женской одежды премиального сегмента столкнулся с падением продаж и высокой конкуренцией. Благодаря...`, href: `/cases/uvelichili-onlayn-prodazhi-v-24-raza-dlya-brenda-odezhdy-za-4-mesyatsa`, label: `VK Ads` },
    { title: `Увеличили онлайн-продажи кофе и чая на 142% для розничной сети`, description: `Розничная сеть премиального кофе и чая столкнулась с высокой конкуренцией и низкой конверсией. Благодаря комплексному...`, href: `/cases/uvelichili-onlayn-prodazhi-kofe-i-chaya-na-142-dlya-roznichnoy-seti`, label: `Яндекс Директ` },
    { title: `Снизили стоимость лида на 42% и увеличили кол-во заявок для HR-сервиса`, description: `ывфывфыв`, href: `/cases/snizili-stoimost-lida-na-42-i-uvelichili-kol-vo-zayavok-dlya-hr-servisa`, label: `VK Ads` },
  ],
};
